# Generated by Django 3.1.7 on 2022-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='Profile_Images'),
        ),
    ]
